language: ruby
rvm:
  - 2.5.7 
  # - 2.0.0
  # - 1.9.3
  # - jruby-19mode
  # - rbx-2
services:
  - postgresql
# before_script:
#   - cd BasketballAPI
#   - bundle install
#   - bundle exec rails db:create
#   - bundle exec rails db:migrate
script: 
  - ""
before_deploy:
  - cd BasketballAPI
deploy:
  provider: heroku 
  api_key:
    secure: NvOGjTpbJlv+OMl9pctSLy3J22umt4KSfzq+fMAqiSyxQywyDos8H3txbRojCBZfRdWPnwsBGng2tvI9dha3J563NNzyb37U00IsAA2eKKcg89fFgV+bbY26lhMqu/E/iPcsrG/+ZDFSBIK1gFgph3jdY1Ia16YmVX5Fj6D7VRPmjbObFx1uzqsUfWIfkNSanCMVY9WXpXIWeE4JJYCfuJAefecwL0Q7PxXFwgmVN4DJNBTO9qY1NMxLL3B3OXFdm0ItDf0msgNBCYgC4JyG9MSBcvcY1dnYpTg3D6VhcBmBCyM/OsxIbvGLmIQD8xdyMOFvNERIaKLfii6/tgcTUxEVY/TeUU6uPM/5YAdOAhQU0l7flOfZ4tGuDTEItVM0+tih3r9E/S0opYdSSTG+PD0pILF1NPSCgvbByJoSohGNvjFCYwu791y4Qx7FWJXtiB1+4qskoGdp5EVvNpGKISITGn6jSlijyzVsSt1eOHa5yDmOL+3xBs43gzXw1wGg2eHaJTbpgNpKxfKriO0nBbTxd1WTpxp1IZs9SKKZ5VcZk8HU8hyVm+NqblYJ65EFHJtC7MXr/Unhl58Q9velknLnDCrxBUZIr6PWUSBZzuKa3S5knxNyUC66UKxU++qZbQW4VsYyiHw0RF5ctTCdLSED9RC4BP2yWEOiTeE4GxI=
  app: gotnext-backend
  on: main
  run:
    - "rails db:migrate"
    - "rails db:seed"