-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAbTx1hotZ2RLs1ja
qomlXp1WZG/4Mi4H1S78kgixNfagCgYIKoZIzj0DAQehRANCAARWKpuMIpwArMcP
Tcj2btWqOkVPFUcZ5ZHtoBU53LIAY7W4Lh9RHEwH93uAndNSyePD2psP+vpZcf9S
UJMVUAhr
-----END PRIVATE KEY-----